name: ovolutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  file_picker: ^10.3.7
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^19.5.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  flutter_widget_from_html: ^0.17.1
  get: ^4.7.3
  glassmorphism_ui: ^0.3.0
  google_fonts: ^6.3.3
  google_sign_in: ^7.2.0
  http: 1.6.0
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.1
  in_app_review: ^2.0.11
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  lottie: ^3.3.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  simple_ripple_animation: ^0.1.0
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  uuid: 4.5.2
  webview_flutter: 4.13.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/onboard/
    - assets/images/homescreen/
    - assets/images/bottom_nav/
    - assets/images/login/
    - assets/images/splash/
    - assets/images/plate_details/
    - assets/images/social/
    - assets/images/menu/
    - assets/animation/
    - assets/fonts/

  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/Albert_Sans/AlbertSans-Regular.ttf
        - asset: assets/fonts/Albert_Sans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Albert_Sans/AlbertSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Albert_Sans/AlbertSans-Light.ttf
          weight: 300
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
          style: italic
    - family: FE-FONT
      fonts:
        - asset: assets/fonts/fe_font/FE-FONT.TTF
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 900
    - family: poppin
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 900
        
